### ISSUE TITLE
AC Download Fails

### ISSUE THREAD

**Issue by jcoker85** [JustaPenguin/assetto-server-manager#1072]
**Describe the bug**
AC Download fails during docker-compose up with default config.yml and docker-compose.yml files. I also tried my own Steam user with no Steam Guard enabled, and the same error occurred. 

**To Reproduce**
1. Attempt to install server manager using docker-compose up command with default config.yml and docker-compose.yml files
2. Multiple errors shown in terminal output

**Expected behavior**
Download should not fail from steamcmd.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18 LTS
 - Docker-Compose Version: 1.28.2, build 67630359
 - Docker Version: 19.03.8, build afacb8b7f0
 
**Additional context**
Below is the entire output from terminal during the installation process:

> Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
> Creating acmansrv_server-manager_1 ... done
> Attaching to acmansrv_server-manager_1
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="initialising Raven monitoring"
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="initialising Prometheus Monitoring"
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="Running migration: Add Internal UUID to Championship Entrants"
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="Running migration: Add Admin Account"
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="Running migration: Add entrants to championship events"
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="Running migration: Add class ID to championship classes"
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="Running migration: Enhance Old Championship Results Files"
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="Running migration: Add Result Screen Time"
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="Running migration: Add Pit Box Definition To Entrants"
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="Running migration: Add Last Seen Version to Accounts"
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="Running migration: Set Server Options Sleep Time to 1"
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="Running migration: enable 'Persist Open Entrants' in Championships"
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="Running migration: Add Theme Choice to Accounts"
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="Running migration: Add Race Weekend examples"
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="Running migration: Add Server Name Template"
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="Running migration: Add Available Cars to Championship Class"
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="Running migration: Change Notification Timer"
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="Running migration: Add Content examples"
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="Running migration: Add Server ID to Scheduled Events"
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="Running migration: Add Loop Per Server to Custom Race"
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="Running migration: Correcting Multiclass Championship incorrect ClassIDs (if any)"
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="Duplicated class id: b4be8a31-79ad-48f0-8395-ebcdd5ced27a in Championship: cef1160e-65bf-4501-923d-4fd4c2d2a968"
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="Running migration: Enable AC Server Logging"
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="Running migration: Convert Account Group to Server ID Group Map"
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="Running migration: Convert Content Manager Description to New Template"
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="Running migration: Add Has Seen Intro Popup to Accounts"
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="Running migration: Enable Event Details Popup"
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="Running migration: Add Default ACSR Gate Options to Championships"
> server-manager_1  | time="2021-02-06T05:35:57Z" level=info msg="Running migration: Add Split Type to Race Weekends"
> server-manager_1  | time="2021-02-06T05:36:02Z" level=info msg="Attempting to install the Assetto Corsa Server (steamid: 302550) to /home/assetto/server-manager/assetto"
> server-manager_1  | WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
> server-manager_1  | Redirecting stderr to '/home/assetto/Steam/logs/stderr.txt'
> server-manager_1  | [  0%] Checking for available updates...
> server-manager_1  | /data/src/common/enum_names.cpp (2194) : Assertion Failed: Missing String for EOSType (-185)
> server-manager_1  | /data/src/common/enum_names.cpp (2194) : Assertion Failed: Missing String for EOSType (-185)
> server-manager_1  | /data/src/common/enum_names.cpp (2194) : Assertion Failed: Missing String for EOSType (-185)
> server-manager_1  | /data/src/common/enum_names.cpp (2194) : Assertion Failed: Missing String for EOSType (-185)
> server-manager_1  | /data/src/common/enum_names.cpp (2194) : Assertion Failed: Missing String for EOSType (-185)
> server-manager_1  | /data/src/common/enum_names.cpp (2194) : Assertion Failed: Missing String for EOSType (-185)
> server-manager_1  | /data/src/common/enum_names.cpp (2194) : Assertion Failed: Missing String for EOSType (-185)
> server-manager_1  | /data/src/common/enum_names.cpp (2194) : Assertion Failed: Missing String for EOSType (-185)
> server-manager_1  | [----] Downloading update (199 of 51871 KB)...
> server-manager_1  | [  0%] Downloading update (3847 of 51871 KB)...
> server-manager_1  | [  7%] Downloading update (6865 of 51871 KB)...
> server-manager_1  | [ 13%] Downloading update (9606 of 51871 KB)...
> server-manager_1  | [ 18%] Downloading update (12323 of 51871 KB)...
> server-manager_1  | [ 23%] Downloading update (14818 of 51871 KB)...
> server-manager_1  | [ 28%] Downloading update (17208 of 51871 KB)...
> server-manager_1  | [ 33%] Downloading update (19708 of 51871 KB)...
> server-manager_1  | [ 37%] Downloading update (22193 of 51871 KB)...
> server-manager_1  | [ 42%] Downloading update (24686 of 51871 KB)...
> server-manager_1  | [ 47%] Downloading update (27430 of 51871 KB)...
> server-manager_1  | [ 52%] Downloading update (29912 of 51871 KB)...
> server-manager_1  | [ 57%] Downloading update (32598 of 51871 KB)...
> server-manager_1  | [ 62%] Downloading update (33842 of 51871 KB)...
> server-manager_1  | [ 65%] Downloading update (35087 of 51871 KB)...
> server-manager_1  | [ 67%] Downloading update (36330 of 51871 KB)...
> server-manager_1  | [ 70%] Downloading update (37694 of 51871 KB)...
> server-manager_1  | [ 72%] Downloading update (38932 of 51871 KB)...
> server-manager_1  | [ 75%] Downloading update (40177 of 51871 KB)...
> server-manager_1  | [ 77%] Downloading update (41540 of 51871 KB)...
> server-manager_1  | [ 80%] Downloading update (42790 of 51871 KB)...
> server-manager_1  | [ 82%] Downloading update (44034 of 51871 KB)...
> server-manager_1  | [ 84%] Downloading update (45273 of 51871 KB)...
> server-manager_1  | [ 87%] Downloading update (46642 of 51871 KB)...
> server-manager_1  | [ 89%] Downloading update (47892 of 51871 KB)...
> server-manager_1  | [ 92%] Downloading update (49142 of 51871 KB)...
> server-manager_1  | [ 94%] Downloading update (50375 of 51871 KB)...
> server-manager_1  | [ 97%] Downloading update (51752 of 51871 KB)...
> server-manager_1  | [ 99%] Downloading update (51871 of 51871 KB)...
> server-manager_1  | /data/src/common/enum_names.cpp (2194) : Assertion Failed: Missing String for EOSType (-185)
> server-manager_1  | /data/src/common/enum_names.cpp (2194) : Assertion Failed: Missing String for EOSType (-185)
> server-manager_1  | /data/src/common/enum_names.cpp (2194) : Assertion Failed: Missing String for EOSType (-185)
> server-manager_1  | /data/src/common/enum_names.cpp (2194) : Assertion Failed: Missing String for EOSType (-185)
> server-manager_1  | /data/src/common/enum_names.cpp (2194) : Assertion Failed: Missing String for EOSType (-185)
> server-manager_1  | /data/src/common/enum_names.cpp (2194) : Assertion Failed: Missing String for EOSType (-185)
> server-manager_1  | /data/src/common/enum_names.cpp (2194) : Assertion Failed: Missing String for EOSType (-185)
> server-manager_1  | /data/src/common/enum_names.cpp (2194) : Assertion Failed: Missing String for EOSType (-185)
> server-manager_1  | [100%] Download complete.
> server-manager_1  | /data/src/common/enum_names.cpp (2194) : Assertion Failed: Missing String for EOSType (-185)
> server-manager_1  | /data/src/common/enum_names.cpp (2194) : Assertion Failed: Missing String for EOSType (-185)
> server-manager_1  | /data/src/common/enum_names.cpp (2194) : Assertion Failed: Missing String for EOSType (-185)
> server-manager_1  | /data/src/common/enum_names.cpp (2194) : Assertion Failed: Missing String for EOSType (-185)
> server-manager_1  | /data/src/common/enum_names.cpp (2194) : Assertion Failed: Missing String for EOSType (-185)
> server-manager_1  | /data/src/common/enum_names.cpp (2194) : Assertion Failed: Missing String for EOSType (-185)
> server-manager_1  | /data/src/common/enum_names.cpp (2194) : Assertion Failed: Missing String for EOSType (-185)
> server-manager_1  | /data/src/common/enum_names.cpp (2194) : Assertion Failed: Missing String for EOSType (-185)
> server-manager_1  | !!! An Error Occurred !!!
> server-manager_1  | -------------------------
> server-manager_1  | 
> server-manager_1  | Failed to initialise server manager. 
> server-manager_1  | 
> server-manager_1  | Your configuration file is probably incorrect, or you haven't followed the instructions in the README properly. 
> server-manager_1  | Please carefully check that your options are set correctly.
> server-manager_1  | 
> server-manager_1  |       Error Details
> server-manager_1  | -------------------------
> server-manager_1  | 
> server-manager_1  | The error occurred attempting to: Install assetto corsa server with steamcmd. Likely you do not have steamcmd installed correctly.
> server-manager_1  | The error more specifically is: exit status 254
> server-manager_1  | 
> server-manager_1  | -------------------------
> server-manager_1  | 
> server-manager_1  | If you need support, you can ask in the RaceDepartment Support thread. Be sure to copy the above errors into your post.
> server-manager_1  | 	
> server-manager_1  | 	Support thread: https://www.racedepartment.com/threads/ac-server-manager.165662/
> server-manager_1  | 
> server-manager_1  | We're really active on the support thread helping everybody with their problems and adding new features.
> server-manager_1  |

**Comment by jmgevers99** [comment]
Im getting the same error, any news on this?

**Comment by celianvdb** [comment]
Same here

**Comment by celianvdb** [comment]
I fixed the issue by building manually the docker image from the last release sources.

**Comment by jcoker85** [comment]
Thanks for the workaround @celianvdb. I'm leaving this open still as it should be fixed/updated on Docker Hub.

**Comment by twigley** [comment]
> Thanks for the workaround @celianvdb. I'm leaving this open still as it should be fixed/updated on Docker Hub.

FYI it looks like the latest tag and the latest build is still 1.7.8 on docker hub.

**Comment by HighPriest** [comment]
Please update the image on docker hub.
It is still failing and it's April...

**Comment by cj123** [comment]
Apologies for the delay in getting this sorted. I've just updated the image to v1.7.9, also available on the 'latest' tag.

**Comment by JaviPG** [comment]
Currently I have the same error with the latest version (v1.7.9) 

![image](https://user-images.githubusercontent.com/1521858/134759138-1264c359-818b-4dfb-bf45-e315367f1c64.png)

**Comment by JaviPG** [comment]
Currently I have the same error with the latest version (v1.7.9). Steam guard is disabled.

![image](https://user-images.githubusercontent.com/1521858/134759444-9632d393-3059-4577-9c1a-de11aa17e27f.png)

**Comment by sjmorrow** [comment]
I have this same error ☝️ . @cj123 Sorry to bother, but do you have a workaround for this? I've been trying to get this fixed for almost a year now.

**Comment by cj123** [comment]
The best way to resolve this issue is to circumvent the steamcmd install entirely. Download the Assetto Corsa Server through your normal steam client, then copy the files over to wherever you have set the `install_path` option in the config.yml.

**Comment by JaviPG** [comment]
I didn’t find a solution. Finally, I followed manual installation (without docker)

**Comment by rmrgh** [comment]
My workaround was to install using another container with steamcmd working.

```
docker run -it -v $PWD/server-install:/data steamcmd/steamcmd:latest +@sSteamCmdForcePlatformType windows +login YOUR_STEAM_LOGIN +force_install_dir /data +app_update 302550 +quit
```

It will probably ask for your password and Steam Guard code if enabled.
